include_configs:
  - ../shapenet/data.yaml

_shapenet_transforms:
  - name: "PointcloudNoise"
    args: { "stddev": 0.005 }
  - name: "SubsamplePointcloud"
    args: { "N": 3000 }
_shapenet_custom_name: "snet-noise3k"
_shapenet_categories: ['02691156-sub']

name: 'shapenet/noise_3k_neural'
geometry: 'neural'

voxel_size: 0.02
kernel_dim: 16

interpolator:
  n_hidden: 2
  hidden_dim: 32
